name: Deploy GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  repository_dispatch:
    types:
      # for dispatch from contentful via webhook
      - deploy
#  schedule:
#    - cron: '*/5 * * * *'

concurrency:
  # to disable multiple parallel jobs during changes in contentful
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  NUXT_ROUTER_BASE_URL: '/'
  FULL_BASE_URL: 'https://20let.esncz.org/'
  CTF_SPACE_ID: ${{ secrets.CTF_SPACE_ID }}
  CTF_CDA_ACCESS_TOKEN: ${{ secrets.CTF_CDA_ACCESS_TOKEN }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Render website
        run: yarn generate

      - name: Deploy to server
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: ./
