name: Deploy to production server

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  repository_dispatch:
    types:
      # for dispatch from contentful via webhook
      - deploy
#  schedule:
#    - cron: '*/5 * * * *'

concurrency:
  # to disable multiple parallel jobs during changes in contentful
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  NUXT_ROUTER_BASE_URL: '/'
  FULL_BASE_URL: 'https://20let.esncz.org/'
  CTF_SPACE_ID: ${{ secrets.CTF_SPACE_ID }}
  CTF_CDA_ACCESS_TOKEN: ${{ secrets.CTF_CDA_ACCESS_TOKEN }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Clear NUXT cache
        run: rm -rf node_modules/.cache

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Render website
        run: yarn generate

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            ARGS: "-rltzvO --delete"
            SOURCE: "dist/"
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            TARGET: ${{ secrets.REMOTE_TARGET }}
